### ISSUE TITLE
Portraits scroll off screen with high companion count

### ISSUE THREAD

**Issue by aureus1** [factubsio/BubbleBuffs#13]
**Describe the bug**
With a high number of companions (i.e. lich playthrough with multiple mercs/pets), the character portraits scroll offscreen making it unable to select some characters to target

**To Reproduce**

1. Have a large number of companions, about 21 did it for me @ 3440x1440 resolution
2. Open bubble buffs menu

**Expected behavior**
All characters should be selectable.  Either via scrolling the portraits or scaling the size down.

**Screenshots**
https://pasteboard.co/6EHP4RDrNnCZ.png

**Additional context**

**Comment by factubsio** [comment]
Are you in town?

Are you using toybox to do gestalt multiple mythics or larger party?

**Comment by howardreith** [comment]
Hey, I'm experiencing this problem as well. I simply have a larger party because I have 5 mercenaries (the party I use) plus all the normal companions (who I'm keeping around for story purposes). Consequently now that I've recruited Greybor I can no longer apply buffs to my main character, and I suspect there's someone else who's probably missing too.

![20221009090554_1](https://user-images.githubusercontent.com/38789146/194758476-4a889cb4-fc4e-442f-b002-b17f7d37edf6.jpg)

Thank you for the amazing mod!

**Comment by factubsio** [comment]
I am not doing stuff to support toybox mega-party sizes, sorry.
